config/routes.rb
Rails.application.routes.draw do
  resources :preys
  resources :dinosaurs
  resources :dinosaur_types
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dinosaur.rb
class Dinosaur < ApplicationRecord
  belongs_to :dinosaur_type
  has_many :dinosaur_preys
  has_many :preys, through: :dinosaur_preys
end

app/models/dinosaur_prey.rb
class DinosaurPrey < ApplicationRecord
  belongs_to :dinosaur
  belongs_to :prey
end

app/models/dinosaur_type.rb
class DinosaurType < ApplicationRecord
  has_many :dinosaurs
  has_many :dinosaur_prey, through: :dinosaurs
  has_many :prey, through: :dinosaur_prey

end

app/models/prey.rb
class Prey < ApplicationRecord
  has_many :dinosaur_preys
  has_many :dinosaurs, through: :dinosaur_preys
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dinosaur_types_controller.rb
class DinosaurTypesController < ApplicationController

  def index
    @types = DinosaurType.all
  end

  def show
    @type = DinosaurType.find(params[:id])
  end

  def new
    @type = DinosaurType.new
  end

  def create
    type = Dinosaur.create(type_params)
    byebug
    # if params[:]
    #   type
    #   redirect_to dinosaur_type_path(type)
    # else
    #   render :new
    #   flash[:alert] = "Try again"
    # end
  end

  # def edit
  #   @type = DinosaurType.find(params(:id))
  # end

  # def update
  #   @type = DinosaurType.find(params(:id))
  #   @type.update(type_params)
  #   redirect_to dinosaur_type_path(@type)
  # end

  def type_params
    params.require(:dinosaur_type).permit(:name)
  end
end

app/controllers/dinosaurs_controller.rb
class DinosaursController < ApplicationController

  def index
    @dinos = Dinosaur.all
  end

  def show
    @dino = Dinosaur.find(params[:id])
  end

  def new
    @dino = Dinosaur.new
  end

# fix DRY someday
  def create
    dino = Dinosaur.new(dino_params)
    if params[:type]
      type = DinosaurType.find_or_create_by(name: params[:type])
      dino.dinosaur_type = type
      if dino.save
        redirect_to dinosaur_path(dino)
      else
        render :new
        flash[:alert] = "Try again, LOSER"
      end
    elsif !params[:dinosaur][:dinosaur_type_id].blank?
      type = DinosaurTyoe.find(params[:dinosaur][:dinosaur_type_id].to_i)
      dino.dinosaur_type = type
      if dino.save
        redirect_to dinosaur_path(dino)
      else
        render :new
        flash[:alert] = "Try again, LOSER"
      end
    end
  end

  def edit
    @dino = Dinosaur.find(params[:id])
  end

  def update
    @dino = Dinosaur.find(params[:id])
    if @dino.update(dino_params)
      redirect_to dinosaur_path(@dino)
    else
      render :edit
      flash[:alert] = "FAILURE"
    end
  end

  def destroy
    @dino = Dinosaur.find(params[:id])
    @dino.destroy
    redirect_to dinosaurs_path
  end


  def dino_params
    params.require(:dinosaur).permit(:name, :weight, :badass_index, prey_ids: [])
  end

end

app/controllers/preys_controller.rb
class PreysController < ApplicationController

  def index
    @preys = Prey.all
  end

  def show
    @prey = Prey.find(params[:id])
  end

  def new
    @prey = Prey.new
  end

  def create
    prey = Prey.create(prey_params)
    if prey
      redirect_to prey_path(prey)
    else
      render :new
      flash[:alert] = "Try again"
    end
  end

  def edit
    @prey = Prey.find(params[:id])
  end

  def update
    @prey = Prey.find(params[:id])
    if @prey.update(prey_params)
      redirect_to prey_path(@prey)
    else
      render :edit
      flash[:alert] = "FAILURE"
    end
  end

  def destroy
    @prey = Prey.find(params[:id])
    @prey.destory
    redirect_to preysaurs_path
  end

  def prey_params
    params.require(:prey).permit(:name, :weight, dinosaur_ids: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dinosaur_types_helper.rb
module DinosaurTypesHelper
end

app/helpers/dinosaurs_helper.rb
module DinosaursHelper
end

app/helpers/preys_helper.rb
module PreysHelper
end

app/views/dinosaur_types/index.html.erb
<h1>Dinosaur Types!</h1>

<% @types.each do |type| %>

<%= type.name %><br />
<%= link_to "See Dinosaurs!", dinosaur_type_path(type) %>
<br /><br />

<% end %>

app/views/dinosaur_types/new.html.erb
<h1>New Dinosaur Type!</h1>

<% if flash[:alert] %>
<%= flash[:alert] %>
<% end %>

<%= form_for @type do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.submit %>
<% end %>


<%= "Thank You!" %>

app/views/dinosaur_types/show.html.erb
<%= "Welcome to the best dinosaur category: #{@type.name}" %>
<br /><br />
<%= "Our Dinosaurs!" %>

<% @type.dinosaurs.each do |dino| %>
<label>Name: </label>
<%= dino.name %><br />
<label>Weight: </label>
<%= dino.weight %><br />
<label>Badass Index: </label>
<%= dino.badass_index %><br />
<%= link_to "More Details", dinosaur_path(dino) %>
<% end %>

app/views/dinosaurs/edit.html.erb
<h1>Edit a Dino!</h1>

<% if flash[:alert] %>
<%= flash[:alert] %>
<% end %>


<%= form_for @dino do |f| %>
<%= f.label :name %>
<%= f.text_field :name %><br />
<%= f.label :weight %>
<%= f.number_field :weight %><br />
<%= f.label :badass_index %>
<%= f.number_field :badass_index %><br />
<%= "Who do you eat?:" %><br />
<%= f.collection_check_boxes :prey_ids, Prey.all, :id, :name %>
<br />
<%= f.submit %>
<br /><br />
<% end %>

<%= "Or Delete your Dino" %><br></br>
<%= link_to "Delete", dinosaur_path(@dino), method: :delete, data: {confirm: "Why?"} %>

app/views/dinosaurs/index.html.erb
<h1>Dinosaurs!</h1>

<% @dinos.each do |dino| %>

<label>Name: </label>
<%= dino.name %><br />
<label>Weight: </label>
<%= dino.weight %><br />
<label>Badass Index: </label>
<%= dino.badass_index %><br />
<label>Category: </label>
<%= link_to dino.dinosaur_type.name, dinosaur_type_path(dino.dinosaur_type) %><br />
<%= link_to "More Details", dinosaur_path(dino) %>
<br /><br />

<% end %>

app/views/dinosaurs/new.html.erb
<h1>Create a Dino!</h1>

<% if flash[:alert] %>
<%= flash[:alert] %>
<% end %>


<%= form_for @dino do |f| %>
<%= f.label :name %>
<%= f.text_field :name %><br />
<%= f.label :weight %>
<%= f.number_field :weight %><br />
<%= f.label :badass_index %>
<%= f.number_field :badass_index %><br />
<%= "Who do you eat?:" %><br />
<%= f.collection_check_boxes :prey_ids, Prey.all, :id, :name %>
<br />
<%= "Choose from existing categories:" %><br />
<%= f.collection_select :dinosaur_type_id, DinosaurType.all, :id, :name, include_blank: true %>
<br /><br />
<%= "Or, create a new category below!" %><br />
<label>Category Name:</label>
<%= text_field_tag :type %><br />
<%= f.submit %>
<% end %>

app/views/dinosaurs/show.html.erb
<h1>Welcome to the show page for <%= @dino.name %></h1>

<label>Name: </label>
<%= @dino.name %><br />
<label>Weight: </label>
<%= @dino.weight %><br />
<label>Badass Index: </label>
<%= @dino.badass_index %><br />
<label>Category: </label>
<%= link_to @dino.dinosaur_type.name, dinosaur_type_path(@dino.dinosaur_type) %>
<label>Prey: </label>
<% @dino.preys.each do |prey| %>
<%= link_to prey.name, prey_path(prey) %><br /><br />
<% end %>

<%= link_to "Edit", edit_dinosaur_path(@dino) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DinosaursApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/preys/index.html.erb
<h1>Prey!</h1>

<% @preys.each do |prey| %>

<label>Name: </label>
<%= prey.name %><br />
<label>Weight: </label>
<%= prey.weight %><br />
<label>More Details: </label><br />
<%= link_to prey.name.capitalize, prey_path(prey) %><br />
<br /><br />
<% end %>

app/views/preys/new.html.erb
<h1>New Dinosaur Food!</h1>

<% if flash[:alert] %>
<%= flash[:alert] %>
<% end %>

<%= form_for @prey do |f| %>
<%= f.label :name %>
<%= f.text_field :name %><br />
<%= f.label :weight %>
<%= f.text_field :weight %><br />
<%= "Who eats you?:" %><br />
<%= f.collection_check_boxes :dinosaur_ids, Dinosaur.all, :id, :name %>


<%= f.submit %>
<% end %>


<%= "Thank You!" %>

app/views/preys/show.html.erb
<h1>Prey!</h1>

<label>Name: </label>
<%= @prey.name %><br />
<label>Weight: </label>
<%= @prey.weight %><br />
<label>Predators: </label>
<% @prey.dinosaurs.each do |dino| %>
<%= link_to dino.name, dinosaur_path(dino) %><br />
<% end %>